import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

/*
  Generated class for the AuditorProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class AuditorProvider {

  constructor(public http: HttpClient) {
    console.log('Hello AuditorProvider Provider');
  }

  public getAuditor(code: string) {
    return this.tempAuditors.filter(it => it.code == code)[0];
  }

  private tempAuditors = [
    {
      "applicationDate": "10/30/2017 4:21",
      "confirmationDate": "10/31/2017 9:37",
      "name": "ไกวัล วัฒนา",
      "address": "12/15 ลุมพินีคอนโดทาวน์ รามอินทรา-หลักสี่",
      "email": "kaiwankub@hotmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "วิศวกรโยธา",
      "code": "RSA.0002",
      "level": "audit",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/2/2017 3:36",
      "confirmationDate": "11/22/2017 3:40",
      "name": "วัชระ ศรีรักษา",
      "address": 173,
      "email": "charadrr18@gmail.com",
      "division": "แขวงทางหลวงชนบทพัทลุง",
      "position": "นายชช่างโยธาชำนาญงาน",
      "code": "wat0895947290",
      "level": "inspector",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/2/2017 6:41",
      "confirmationDate": "11/3/2017 6:12",
      "name": "อาติยา เครือวรรณ",
      "address": "97/2 ถ.อภัย ต.กาฬสินธุ์ อ.เมือง จ.กาฬสินธุ์",
      "email": "artiya_k@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 16 (กาฬสินธุ์)",
      "position": "วิศวกรโยธา (พร.)",
      "code": "RSI.0124",
      "level": "inspector",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/2/2017 8:53",
      "confirmationDate": "11/3/2017 6:13",
      "name": "นายสุรศักดิ์  ไกรพินิจ",
      "address": "บ้านคำเกิ่้ม หมู่ 8 ต.อาจสามารถ อ.เมือง จ.นครพนม",
      "email": "tore16@gmail.com",
      "division": "แขวงทางหลวงชนบทนครพนม",
      "position": "ผู้อำนวยการแขวงทางหลวงชนบทนครพนม",
      "code": "RSI.0121",
      "level": "inspector",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/6/2017 5:06",
      "confirmationDate": "11/9/2017 6:36",
      "name": "วิโรจน์ แป้นรส",
      "address": "522/22 ม.7 ต.ไสไทย อ.เมือง จ.กระบี่",
      "email": "wiros2522@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 14 (กระบี่)",
      "position": "นายช่างโยธาปฎิบัติงาน",
      "code": "RSI.0082",
      "level": "inspector",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/7/2017 4:59",
      "confirmationDate": "11/9/2017 6:37",
      "name": "นายศรุต รุ่งโรจน์นิมิตชัย",
      "address": "สำนักงานทางหลวงชนบทที่7(อุบลราชธานี) 130 ถนนคลังอาวุธ ตำบลขามใหญ่ อำเภอเมือง จังหวัดอุบลราชธานี 34000",
      "email": "sarut_999@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 7 (อุบลราชธานี)",
      "position": "วิศวกรโยธาชำนาญการ",
      "code": "RSI.0114",
      "level": "inspector",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/8/2017 2:30",
      "confirmationDate": "11/9/2017 6:38",
      "name": "นายดำรงศักดิ์ คงช่วย",
      "address": "สทช.ที่14(กระบี่)171/37 ม.7 ต.ไสยไทย อ.เมือง จ.กระบี่",
      "email": "khongmark3@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 14 (กระบี่)",
      "position": "วิศวกรโยธาชำนาญการพิเศษ",
      "code": "RSA.0010",
      "level": "audit",
      "trainBy": "",
      "trainOn": ""
    },
    {
      "applicationDate": "11/16/2017 4:56",
      "confirmationDate": "11/16/2017 8:30",
      "name": "ธเนศ มุณีแนม",
      "address": "15 หมู่ 6 ต.ทุ่งขมิ้น อ.นาหม่อม จ.สงขลา 90310",
      "email": "nongkubtec@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 12 (สงขลา)",
      "position": "วิศวกรโยธา",
      "code": "RSI.0070",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/7/2560"
    },
    {
      "applicationDate": "11/16/2017 9:29",
      "confirmationDate": "11/16/2017 10:26",
      "name": "ภาคภูมิ  ไชยศรี",
      "address": "104 ม.3 ต.วังทอง อ.วังสมบูณ์ จ.สระแก้ว",
      "email": "pakpoom.c@hotmail.com",
      "division": "แขวงทางหลวงชนบทสระแก้ว",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0053",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/16/2017 9:33",
      "confirmationDate": "11/16/2017 10:26",
      "name": "วินิตย์  แหมา",
      "address": "328 ม.14 ต.บ้านกล้วย อ.เมือง จ.สุโขทัย 64000",
      "email": "winit_x_85@hotmail.com",
      "division": "แขวงทางหลวงชนบทสุโขทัย",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0150",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทางร่วมกับ 9 มหาวิทยาลัย",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/16/2017 11:54",
      "confirmationDate": "11/17/2017 8:55",
      "name": "นายศรายุธ   ศรีชู",
      "address": "184/35  ม.11  ต.โคกหล่อ อ.เมือง จ.ตรัง",
      "email": "sara_k6@hotmail.co.th",
      "division": "แขวงทางหลวงชนบทหวัดตรัง",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0084",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทางร่วมกับที่ปรึกษา",
      "trainOn": "9/7/2017"
    },
    {
      "applicationDate": "11/16/2017 16:20",
      "confirmationDate": "11/17/2017 8:54",
      "name": "นายภูริเดช โคตะนิวงษ์",
      "address": "บ้านพักแขวงทางหลวงชนบทหนองคาย",
      "email": "puridet64@gmail.com",
      "division": "แขวงทางหลวงชนบทหนองคาย",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0110",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "11/17/2017 9:09",
      "confirmationDate": "11/21/2017 4:26",
      "name": "พิชชา วชิโรปถัมภ์",
      "address": "367/5 มบ.บุษราคัม ถ.จรัญสนิทวงศ์ แขวงอรุณอมรินทร์ เขตบางกอกน้อย กรุงเทพฯ 10700",
      "email": "pitcha.wachi@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0019",
      "level": "audit",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/28/2017"
    },
    {
      "applicationDate": "11/17/2017 15:52",
      "confirmationDate": "11/20/2017 1:59",
      "name": "นายเฉลิมพงษ์ จันทร์สำเภา",
      "address": "720 หมู่6 ต.ทับคล้อ อ.ทับคล้อ จ.พิจิตร",
      "email": "chpongs@gmail.com",
      "division": "แขวงทางหลวงชนบทพิจิตร",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0130",
      "level": "inspector",
      "trainBy": "มหาวิทยาลัยเชียงใหม่",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/18/2017 11:11",
      "confirmationDate": "11/19/2017 3:53",
      "name": "นายธนวรรธห์ จริงสันเทียะ",
      "address": "204 หมู่16 ต.อ่าวน้อย อ.เมือง จ.ประจวบคีรีขันธ์",
      "email": "coko.thanawat@gmail.com",
      "division": "แขวงทางหลวงชนบทราชบุรี",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0009",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "11/20/2017 3:20",
      "confirmationDate": "11/20/2017 4:06",
      "name": "กรภัทร ราชคฤห์",
      "address": "1009/10 ถ.สวรรค์วิถ๊ ต.นครสวรรค์ตก อ.เมือง จ.นครสวรรค์",
      "email": "ratchakeak@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 8 (นครสวรรค์)",
      "position": "วิศวกรโยธา (พร.)",
      "code": "RSI.0126",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/20/2017 3:44",
      "confirmationDate": "11/20/2017 4:03",
      "name": "กิตติภรณ์  พ่วงสุข",
      "address": "156 ม.2 ต.เนินมะปราง อ.เนินมะปราง จ.พิษณุโลก",
      "email": "kittiporn26@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "เจ้าหน้าที่วิเคราะห์นโยบายและแผน",
      "code": "RSI.0065",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทร่วมกับ 9 มหาวิทยาลัยของรัฐ",
      "trainOn": "9/7/2017"
    },
    {
      "applicationDate": "11/20/2017 9:03",
      "confirmationDate": "11/21/2017 2:36",
      "name": "นฤมล  แก้วเปี้ย",
      "address": "67 หมู่4 ต.แสนตอ อ.น้ำปาด จ.อุตรดิตถ์ 53110",
      "email": "naruemon.rsa@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "เจ้าหน้าที่วิเคราะห์นโยบายและแผน",
      "code": "RSI.0023",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทร่วมกับ 9 มหาวิทยาลัยของรัฐ",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/20/2017 9:28",
      "confirmationDate": "11/21/2017 2:36",
      "name": "ปราญชลี",
      "address": "บ้านเลขที่ 9 ถ.ริมทางรถไฟ ต.ท่าศาลา อ.เมือง จ.เชียงใหม่ 50000",
      "email": "jjviewtoro@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "เจ้าหน้าที่วิเคราะห์นโยบายและแผน",
      "code": "RSI.0142",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทร่วมกับเก้ามหาวิทยาลัยของรัฐ",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/20/2017 16:38",
      "confirmationDate": "11/21/2017 2:36",
      "name": "นายปวินท์วัฒน์ ปัญญาวงค์",
      "address": "เลขที่ 40 หมู่ที่ 3 ตำบลหนองพังค่า อำเภอเมือง จังหวัดอุทัยธานี",
      "email": "pawinwat.pun@gmail.com",
      "division": "แขวงทางหลวงชนบทอุทัยธานี",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0143",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "11/21/2017"
    },
    {
      "applicationDate": "11/21/2017 2:51",
      "confirmationDate": "11/21/2017 2:52",
      "name": "ไชยรัตน์ มุขศรี",
      "address": "136 ซ.อินทามระ 17 ถ.สุทธิสารวินิจฉัย แขวงสามเสนใน เขตพญาไท กทม 10400",
      "email": "auto.chairat@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "วิศวกรโยธา",
      "code": "RSA.0007",
      "level": "audit",
      "trainBy": "Vicroads",
      "trainOn": "8/16/2017"
    },
    {
      "applicationDate": "11/21/2017 8:59",
      "confirmationDate": "11/22/2017 2:05",
      "name": "ชัยวิชิต  พรีพรม",
      "address": "อ.เมืองนครราชสีมา",
      "email": "u-kem@hotmail.com",
      "division": "แขวงทางหลวงชนบทนครราชสีมา",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0041",
      "level": "inspector",
      "trainBy": "ดร.ไกรวัล",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/22/2017 9:05",
      "confirmationDate": "11/24/2017 6:17",
      "name": "นายบูรพา วงศ์ใหญ่",
      "address": "260 หมู่ 6 ต.สนามชัย อ.เมือง จ.สุพรรณบุรี",
      "email": "songkrany@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 18 (สุพรรณบุรี)",
      "position": "นายช่างโยธาปฎิบัติงาน",
      "code": "RSI.0014",
      "level": "inspector",
      "trainBy": "สำนักส่วนตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "11/23/2017 4:09",
      "confirmationDate": "11/24/2017 6:18",
      "name": "มนูญ ชาดิษฐ",
      "address": "260 ม.4 ต.สนามชัย อ.เมือง จ.สุพรรณบุรี",
      "email": "m.chadit@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 18 (สุพรรณบุรี)",
      "position": "วิศวกรโยธา",
      "code": "RSI.0016",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัย",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "11/23/2017 6:17",
      "confirmationDate": "11/24/2017 6:19",
      "name": "วุฒิชัย  ธรรมวงศ์ชัย",
      "address": "กรมทางหลวงชนบท",
      "email": "bom364@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "Auditor",
      "code": "RSA.0029",
      "level": "audit",
      "trainBy": "Vic Roads",
      "trainOn": "10/16/2017"
    },
    {
      "applicationDate": "11/24/2017 3:01",
      "confirmationDate": "11/24/2017 6:19",
      "name": "ณัฏฐิตา สุวนันทวงศ์",
      "address": "164/745 หมู่ที่1 ต.พิมลราช อ.บางบัวทอง จ.นนทบุรี",
      "email": "nattita2orsa@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "นักวิเคราะห์นโยบายและแผน",
      "code": "RSI.0007",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "11/27/2017 6:56",
      "confirmationDate": "11/28/2017 16:50",
      "name": "ชณัตพร",
      "address": "กรมทางหลวงชนบท",
      "email": "chanatt.ph@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "ผ่องใส",
      "code": "RSI.0004",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทและ9มหาวิทยาลัยของรัฐ",
      "trainOn": "8/21/2017"
    },
    {
      "applicationDate": "11/27/2017 9:37",
      "confirmationDate": "11/28/2017 16:50",
      "name": "นายธนกฤต  เกตุสงเคราะห์",
      "address": "299 ม.13 ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000",
      "email": "tana.tumm@hotmail.com",
      "division": "แขวงทางหลวงชนบทสกลนคร",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0101",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "11/28/2017 3:38",
      "confirmationDate": "11/28/2017 16:50",
      "name": "นายนรพนธ์ บุระชัด",
      "address": "17/2 ม.3 ต.พะตง อ.หาดใหญ่ จ.สงขลา 90230",
      "email": "bam_nara@hotmail.com",
      "division": "แขวงทางหลวงชนบทหวัดยะลา",
      "position": "นายช่างโยธา",
      "code": "RSI.0073",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/7/2017"
    },
    {
      "applicationDate": "11/28/2017 8:26",
      "confirmationDate": "11/28/2017 16:50",
      "name": "ชุติมันต์ แกว่นสุริยการ",
      "address": "5/5 ม.4 ต.คุ้งสำเภา อ.มโนรมย์ จ.ชัยนาท",
      "email": "toyota6262@hotmail.com",
      "division": "แขวงทางหลวงชนบทชัยนาท",
      "position": "นายช่างโยธา (พร.)",
      "code": "RSI.0043",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "8/28/2017"
    },
    {
      "applicationDate": "11/29/2017 2:11",
      "confirmationDate": "11/29/2017 7:42",
      "name": "นายสมบัติ วรรณพงษ์",
      "address": "แขวงทางหลวงชนบทตาก",
      "email": "sbond1440@gmail.com",
      "division": "แขวงทางหลวงชนบทตาก",
      "position": "วิศวกรโยธาชำนาญการ",
      "code": "RSI.0157",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/29/2017 3:59",
      "confirmationDate": "11/29/2017 7:41",
      "name": "จิรวดี ปิ่นเกษร",
      "address": "196/17 หมู่บ้าน ช.รุ่งเรือง 6 ซ.10/3 ถ.บางกรวย-ไทรน้อย ต.บางรักพัฒนา อ.บางบัวทอง จ.นนทบุรี 11110",
      "email": "jirawadee.pin@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "เจ้าหน้าที่วิเคราะห์นโยบายและแผน",
      "code": "RSI.0093",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทและ9มหาวิทยาลัยของรัฐ",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "11/29/2017 4:00",
      "confirmationDate": "11/29/2017 7:42",
      "name": "นายสิทธิชัย  เจริญรบ",
      "address": "121 หมู่3 บ้านโคกงาม อำเภอเมือง  จังหวัดบึงกาฬ",
      "email": "Sitthichai.drr@gmail.com",
      "division": "แขวงทางหลวงชนบทบึงกาฬ",
      "position": "วิศวกรโยธา พร.",
      "code": "RSI.0117",
      "level": "inspector",
      "trainBy": "สำนักอำนวยความปลอดภัย",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "11/29/2017 7:08",
      "confirmationDate": "11/29/2017 7:41",
      "name": "นายชัยทัด  บุญเกิด",
      "address": "360 หมู่4 ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา",
      "email": "De_lay2012@hotmail.com",
      "division": "แขวงทางหลวงชนบทฉะเชิงเทรา",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0039",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท และ9มหาวิทยาลัยของรัฐ",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/29/2017 7:48",
      "confirmationDate": "11/29/2017 8:14",
      "name": "นายคลังวิชญ์  อุทัยเรือง",
      "address": "409 หมู่ 3 ต.หนองชาก อ.บ้านบึง จ.ชลบุรี",
      "email": "klungwich@gmail.com",
      "division": "แขวงทางหลวงชนบทชลบุรี",
      "position": "ผอ.บทช.บาละมุง",
      "code": "RSI.0035",
      "level": "inspector",
      "trainBy": "สำนักอำนวยความปลอดภัย",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/29/2017 8:01",
      "confirmationDate": "11/29/2017 8:14",
      "name": "นิภาภรณ์",
      "address": "224 หมู่ 7 บ้านโกรกเดือนห้า  ตำบลสุรนารี  อำเภอเมือง  จังหวัดนครราชสีมา",
      "email": "noolek_2036@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 5 (นครราชสีมา)",
      "position": "วิศวกรโยธา (พร.)",
      "code": "RSI.0103",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/11/2017"
    },
    {
      "applicationDate": "11/30/2017 3:05",
      "confirmationDate": "12/8/2017 2:05",
      "name": "นายนฤชิต   ชาตะบุตร",
      "address": "311 ม.1 ต.หนองไผ่ อ.เมือง จ.อุดรธานี",
      "email": "nrchit@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 15 (อุดรธานี)",
      "position": "วิศวกรโยธาชำนาญการพิเศษ",
      "code": "RSA.0013",
      "level": "audit",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/28/2017"
    },
    {
      "applicationDate": "11/30/2017 4:19",
      "confirmationDate": "12/8/2017 2:06",
      "name": "นายวรวุธ เพ็ชร์รัตน์",
      "address": "21/1 ม.6 ถ.สายสนามบิน ต.ควนลัง อ.หาดใหญ่ จ.สงขลา",
      "email": "kvorravut@hotmail.co.th",
      "division": "สำนักงานทางหลวงชนบทที่ 12 (สงขลา)",
      "position": "วิศวกรโยธา(พร.)",
      "code": "RSI.0080",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทและ9มหาวิทยาลัยของรัฐ",
      "trainOn": "9/7/2017"
    },
    {
      "applicationDate": "11/30/2017 6:57",
      "confirmationDate": "12/8/2017 2:06",
      "name": "กฤษฎิ์ เมลืองนนท์",
      "address": "69/61 หมู่บ้านฟ้านันทวัน ถ.หทัยราษฎร์ แขวงมีนบุรี เขตมีนบุรี กรุงเทพฯ 10510",
      "email": "krityonex@gmail.com",
      "division": "สำนักส่งเสริมการพัฒนาทางหลวงท้องถิ่น",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0127",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/30/2017 7:08",
      "confirmationDate": "12/8/2017 2:06",
      "name": "นายเตชวิทย์  ชูประยูร",
      "address": "54/61 ซ.เพิ่มสิน29 แขวงคลองถนน เขตสายไหม กทม. 10220",
      "email": "korphai238@hotmail.com",
      "division": "สำนักส่งเสริมการพัฒนาทางหลวงท้องถิ่น",
      "position": "วิศกรโยธา (พร.)",
      "code": "RSI.0132",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/30/2017 7:08",
      "confirmationDate": "12/8/2017 2:06",
      "name": "นายธนานันต์ จิระณรงค์ศิริ",
      "address": "107/30 จรัญฯ 23/1 แขวงบางขุนศรี เขตบางกอกน้อย กรุงเทพฯ",
      "email": "onewin0156@gmail.com",
      "division": "สำนักส่งเสริมการพัฒนาทางหลวงท้องถิ่น",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0136",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัยงานทา",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "11/30/2017 7:18",
      "confirmationDate": "12/8/2017 2:07",
      "name": "วิริยะ โยคะสิงห์",
      "address": "79 ม.1 ถ.สุวรรณศร ต.เกาะหวาย อ.ปากพลี จ.นครนายก 26130",
      "email": "neng_44@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 13 (ฉะเชิงเทรา)",
      "position": "วิศวกรโยธาปฎิบัติการ",
      "code": "RSI.0057",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "11/30/2017 10:20",
      "confirmationDate": "12/8/2017 2:08",
      "name": "นายวรินทร์  สิสาริกร",
      "address": "335/1 หมู่2 ต.แสนตอ อ.ขาณุวรลักษณบุรี จ.กำแพงเพชร 62130",
      "email": "wary1146@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 8 (นครสวรรค์)",
      "position": "วิศวกรโยธาชำนาญการ",
      "code": "RSA.0028",
      "level": "audit",
      "trainBy": "Vicroads",
      "trainOn": "8/17/2017"
    },
    {
      "applicationDate": "12/1/2017 7:31",
      "confirmationDate": "12/8/2017 2:08",
      "name": "นายอาคม พงษ์วนานุรักษ์",
      "address": "27 หมู่ 4 ถนนมาลัยแมน ตำบลรั้วใหญ่ อำเภอเมือง จังหวัดสุพรรณบุรี",
      "email": "kom.ve_22@hotmail.com",
      "division": "แขวงทางหลวงชนบทสุพรรณบุรี",
      "position": "นายช่างโยธา(พร.)",
      "code": "RSI.0028",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "12/1/2017 10:58",
      "confirmationDate": "12/8/2017 2:09",
      "name": "บัณฑิต  ศิริแพทย์",
      "address": "31/2 ม.8 ต.ปากกราน อ.พระนครศรีอยุธยา จ.พระนครศรีอยุธยา",
      "email": "netcrab@hotmail.com",
      "division": "แขวงทางหลวงชนบทอ่างทอง",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0013",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัยงานทาง กรมทางหลวงชนบท",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "12/4/2017 1:56",
      "confirmationDate": "12/8/2017 2:09",
      "name": "นายอรรถพล  แรกข้าว",
      "address": "22/1 หมู่14 ต.ท่าวังทอง อ.เมือง จ.พะเยา",
      "email": "big-big36@hotmail.com",
      "division": "แขวงทางหลวงชนบทพะเยา",
      "position": "นายช่างโยธา",
      "code": "RSI.0161",
      "level": "inspector",
      "trainBy": "นายอรรถพล แรกข้าว",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "12/4/2017 2:30",
      "confirmationDate": "12/8/2017 2:09",
      "name": "นายสมยศ  จันทวงษ์",
      "address": "37 ม.9 ต.หนองยาว อ.เมือง จ.สระบุรี 18000",
      "email": "kay-korat@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 2 (สระบุรี)",
      "position": "ผู้อำนวยการส่วนบูรณะ",
      "code": "RSI.0059",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทและ 9 มหาวิทยาลัยของรัฐ",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "12/4/2017 7:24",
      "confirmationDate": "12/8/2017 2:09",
      "name": "นายลิขิต  แก้วศิริ",
      "address": "127 ถนนมิตรภาพ  กม.14 ต.สำราญ อ.เมือง จ.ขอนแก่น",
      "email": "Likit2515@yahoo.co.th",
      "division": "สำนักงานทางหลวงชนบทที่ 6 (ขอนแก่น)",
      "position": "วิศวกรโยธาชำนาญการ",
      "code": "RSI.0111",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบทร่วมกับมหาวิทยาลัย",
      "trainOn": "9/11/2017"
    },
    {
      "applicationDate": "12/8/2017 8:11",
      "confirmationDate": "12/8/2017 9:11",
      "name": "pongsakon kongprathom",
      "address": "264 ม.2 ต.น้ำบ่อหลวง อ.สันป่าตอง จ.เชียงใหม่",
      "email": "k.pongsakon@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 10 (เชียงใหม่)",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0144",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยทางถนน",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "12/8/2017 9:04",
      "confirmationDate": "12/8/2017 9:12",
      "name": "นางสาวณภัทร  เอี่ยมสีใส",
      "address": "158/1 ม.6 ต.วัดดาว อ.บางปลาม้า จ.สพพรรณบุรี 72150",
      "email": "naphat.phueng@gmail.com",
      "division": "สำนักก่อสร้างสะพาน",
      "position": "วิศวกรโยธา(พร.)",
      "code": "RSI.0006",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/21/2017"
    },
    {
      "applicationDate": "12/13/2017 8:42",
      "confirmationDate": "12/18/2017 7:16",
      "name": "อดิศัย ทองไทย",
      "address": "ขทช.พังงา ต.ถ้ำน้ำผุด อ.เมือง จ.พังงา 82000",
      "email": "migaza25@gmail.com",
      "division": "แขวงทางหลวงชนบทพังงา",
      "position": "นายช่างโยธาอาวุโส",
      "code": "RSI.0090",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/7/2017"
    },
    {
      "applicationDate": "12/14/2017 9:46",
      "confirmationDate": "12/18/2017 7:16",
      "name": "นายทนงศักดิ์   ชนะ",
      "address": "225 ม.12 ต.บ่อหลวง อ.ฮอด จ.เชียงใหม่ 50240",
      "email": "thanongsak-20@hotmail.com",
      "division": "แขวงทางหลวงชนบทแม่ฮ่องสอน",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0134",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/18/2017"
    },
    {
      "applicationDate": "12/15/2017 8:37",
      "confirmationDate": "12/18/2017 7:18",
      "name": "นายนิเวศน์ สุยะ",
      "address": "110 ม.3 ต.สันมหาพน อ.แม่แตง จ.ชม 50150",
      "email": "niwate.s@hotmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 10 (เชียงใหม่)",
      "position": "นาบช่างโยธาชำนาญงาน",
      "code": "RSA.0014",
      "level": "audit",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/28/2017"
    },
    {
      "applicationDate": "12/15/2017 9:07",
      "confirmationDate": "12/18/2017 7:18",
      "name": "นางอริยา สะมะทอง",
      "address": "330 ม.1 ต.เขาใหญ่ อ.ชะอำ จ.เพชรบุรี",
      "email": "da.mamakiss@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 4 (เพชรบุรี)",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0027",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "12/17/2017 14:05",
      "confirmationDate": "12/18/2017 7:17",
      "name": "รณชัย เลิกลา",
      "address": "9 หมู่ 9 ต.น้ำริด อ.เมือง จ.อุตรดิตถ์",
      "email": "rookkavazung@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 9 (อุตรดิตถ์)",
      "position": "นายช่างโยธา",
      "code": "RSI.0147",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/18/2017"
    },
    {
      "applicationDate": "12/18/2017 8:19",
      "confirmationDate": "12/18/2017 9:43",
      "name": "เล็กชัย ตาแล",
      "address": "44/1 หมู่ที่ 11 ตำบลสะเดียง อำเภอเมือง จังหวัดเพชรบูรณ์",
      "email": "lek1093@hotmail.com",
      "division": "แขวงทางหลวงชนบทเพชรบูรณ์",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0148",
      "level": "inspector",
      "trainBy": "สำนักตรวจสอบความปลอดภัย",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "1/29/2018 4:43",
      "confirmationDate": "2/6/2018 1:41",
      "name": "อนุเทพ อุตมกูล",
      "address": "40 ม.3 ต.หนองพังค่า อ.เมือง จ.อุทัยธานี 61000",
      "email": "uthaithani@drr.go.th",
      "division": "แขวงทางหลวงชนบทอุทัยธานี",
      "position": "ผู้อำนวยการแขวงทางหลวงชนบทอุทัยธานี",
      "code": "RSI.0160",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/21/2017"
    },
    {
      "applicationDate": "2/5/2018 10:06",
      "confirmationDate": "2/6/2018 1:41",
      "name": "พ.อ.อ.สัมฤทธิ์  ศรีกองหนุน",
      "address": "8/3 ต.บางหญ้าแพรก อ.เมือง จ.สมุทรสาคร",
      "email": "zicmon@hotmail.com",
      "division": "แขวงทางหลวงชนบทสมุทรสาคร",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0024",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "2/24/2018"
    },
    {
      "applicationDate": "2/6/2018 1:40",
      "confirmationDate": "2/6/2018 1:41",
      "name": "ชาครีย์ บำรุงวงศ์",
      "address": "9 paholyothin road",
      "email": "chakreeb@gmail.com",
      "division": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "position": "วิศวกรโยธาเชี่ยวชาญ",
      "code": "RSA.0005",
      "level": "audit",
      "trainBy": "Vicroads",
      "trainOn": "8/16/2017"
    },
    {
      "applicationDate": "2/9/2018 7:25",
      "confirmationDate": "2/13/2018 7:30",
      "name": "นายสุเทพ  กุลศรี",
      "address": "127 ถ.มิตรภาพ(กม.14) ต.สำราญ  อ.เมือง  จ.ขอนแก่น  40000",
      "email": "suthepkulsri@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 6 (ขอนแก่น)",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0118",
      "level": "inspector",
      "trainBy": "สำนักงานอำนวยความปลอดภัยงานทาง",
      "trainOn": "9/11/2017"
    },
    {
      "applicationDate": "2/14/2018 6:43",
      "confirmationDate": "2/14/2018 7:30",
      "name": "นายบวร  เวฬุวนารักษ์",
      "address": "96 หมู่3 ต.ไก่คำ อ.เมือง จ.อำนาจเจริญ",
      "email": "noomzah_ce@hotmail.com",
      "division": "แขวงทางหลวงชนบทอำนาจเจริญ",
      "position": "วิศวกรโยธา",
      "code": "RSI.0104",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "2/14/2018 7:59",
      "confirmationDate": "2/16/2018 7:17",
      "name": "นายธนกร  โทสันทัด",
      "address": "307/27 ถ.ถีนานนท์ อ.เมือง จ.มหาสารคาม",
      "email": "tanagon_a11@hotmail.com",
      "division": "แขวงทางหลวงชนบทมหาสารคาม",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0100",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "9/14/2017"
    },
    {
      "applicationDate": "2/16/2018 8:03",
      "confirmationDate": "2/16/2018 8:05",
      "name": "นายวิชัย ทรงตระกูล",
      "address": "1 หมู่ 3 ต.สวนพริก อ.พระนครศรีอยุธยา",
      "email": "wc-1111.z@hotmail.com",
      "division": "แขวงทางหลวงชนบทพระนครศรีอยุธยา",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0020",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทางร่วมกับ 9 มหาวิทยาลัยของรัฐ",
      "trainOn": "8/24/2017"
    },
    {
      "applicationDate": "2/21/2018 2:51",
      "confirmationDate": "2/22/2018 3:49",
      "name": "นายสิทธิพงษ์ จรรยาสุคนธ์",
      "address": "224 หมู่ 7 ถนนมิตรภาพ-หนองปลิง ตำบลสุรนารี อำเภอเมืองนครราชสีมา จังหวัดนครราชสีมา 30000",
      "email": "sitthiphong2508@icloud.com",
      "division": "สำนักงานทางหลวงชนบทที่ 5 (นครราชสีมา)",
      "position": "นายช่างโยธาชำนาญงาน",
      "code": "RSI.0060",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/31/2017"
    },
    {
      "applicationDate": "2/23/2018 8:00",
      "confirmationDate": "2/27/2018 4:32",
      "name": "นายนริศ ฟองคำสี",
      "address": "ที่อยู่ 99/10 หมู่ 2 ตำบลสวนใหญ่ อำเภอเมือง จังหวัดนนทบุรี 11000",
      "email": "narit_14811@hotmail.com",
      "division": "แขวงทางหลวงชนบทนนทบุรี",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0011",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง กรมทางหลวงชนบท",
      "trainOn": "8/21/2017"
    },
    {
      "applicationDate": "2/27/2018 2:50",
      "confirmationDate": "2/27/2018 4:33",
      "name": "นายดลวัฒน์  ยอดบุญลือ",
      "address": "165/3 หมู่1 ต.รอบเวียง อ.เมือง จ.เชียงราย 57000",
      "email": "donl9@hotmail.com",
      "division": "แขวงทางหลวงชนบทพะเยา",
      "position": "นายช่างโยธาปฏิบัติงาน",
      "code": "RSI.0131",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/18/2017"
    },
    {
      "applicationDate": "2/27/2018 3:31",
      "confirmationDate": "2/27/2018 4:33",
      "name": "นายนราศักดิ์ สันสี",
      "address": "84 หมู่ 9 ต.ท่าข้าวเปลือก อ.แม่จัน จ.เชียงราย",
      "email": "donl888@hotmail.com",
      "division": "แขวงทางหลวงชนบทพะเยา",
      "position": "นายช่างโยธา (พร.)",
      "code": "RSI.0137",
      "level": "inspector",
      "trainBy": "สำนักงานตรวจสอบความปลอดภัยงานทาง",
      "trainOn": "9/18/2017"
    },
    {
      "applicationDate": "3/5/2018 2:34",
      "confirmationDate": "3/9/2018 3:20",
      "name": "นายหยา หัสสะ",
      "address": "330 ม.1 ต.เขาใหญ่ อ.ชะอำ จ.เพชรบุรี",
      "email": "banghya58@gmail.com",
      "division": "แขวงทางหลวงชนบทเพชรบุรี",
      "position": "วิศวกรโยธาชำนาญการ",
      "code": "RSI.0025",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "3/5/2018"
    },
    {
      "applicationDate": "3/12/2018 3:04",
      "confirmationDate": "3/19/2018 7:01",
      "name": "นายธัชธรรม์  มังกรแก้ว",
      "address": "379 ม.4 ต.วังเย็น อ.แปลงยาว จ.ฉะเชิงเทรา 24190",
      "email": "thattham23@gmail.com",
      "division": "สำนักงานทางหลวงชนบทที่ 13 (ฉะเชิงเทรา)",
      "position": "วิศวกรโยธาปฏิบัติการ",
      "code": "RSI.0046",
      "level": "inspector",
      "trainBy": "กรมทางหลวงชนบท",
      "trainOn": "8/31/2017"
    }
  ];

}
